[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = "src/core/config.lua"
before = "main.lua"
name = "overflow/core/config"

[[patches]]
[patches.module]
source = "src/core/slots.lua"
before = "main.lua"
name = "overflow/core/slots"

[[patches]]
[patches.module]
source = "src/core/stacking.lua"
before = "main.lua"
name = "overflow/core/stacking"

[[patches]]
[patches.module]
source = "src/integrations/overrides.lua"
before = "main.lua"
name = "overflow/integrations/overrides"

[[patches]]
[patches.module]
source = "src/hooks/card.lua"
before = "main.lua"
name = "overflow/hooks/card"

[[patches]]
[patches.module]
source = "src/hooks/button_callbacks.lua"
before = "main.lua"
name = "overflow/hooks/button_callbacks"

[[patches]]
[patches.module]
source = "src/ui/actions.lua"
before = "main.lua"
name = "overflow/ui/actions"

[[patches]]
[patches.module]
source = "src/ui/config_tab.lua"
before = "main.lua"
name = "overflow/ui/config_tab"

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["Overflow.lua"]

[[patches]]
[patches.module]
source = "localization/en-us.lua"
before = "main.lua"
name = "overflow/localization/en-us"

[[patches]]
[patches.module]
source = "localization/zh_CN.lua"
before = "main.lua"
name = "overflow/localization/zh_CN"
